// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.28.3
// source: proxy/artx/config.proto

package artx

import (
	protocol "github.com/xtls/xray-core/common/protocol"
	tls "github.com/xtls/xray-core/transport/internet/tls"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Account struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Psk           string                 `protobuf:"bytes,1,opt,name=psk,proto3" json:"psk,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_proxy_artx_config_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_artx_config_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_proxy_artx_config_proto_rawDescGZIP(), []int{0}
}

func (x *Account) GetPsk() string {
	if x != nil {
		return x.Psk
	}
	return ""
}

type FallbackConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Enabled       bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	Origin        string                 `protobuf:"bytes,2,opt,name=origin,proto3" json:"origin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FallbackConfig) Reset() {
	*x = FallbackConfig{}
	mi := &file_proxy_artx_config_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FallbackConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FallbackConfig) ProtoMessage() {}

func (x *FallbackConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_artx_config_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FallbackConfig.ProtoReflect.Descriptor instead.
func (*FallbackConfig) Descriptor() ([]byte, []int) {
	return file_proxy_artx_config_proto_rawDescGZIP(), []int{1}
}

func (x *FallbackConfig) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *FallbackConfig) GetOrigin() string {
	if x != nil {
		return x.Origin
	}
	return ""
}

type ServerConfig struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Users          []*protocol.User       `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	TlsSettings    *tls.Config            `protobuf:"bytes,2,opt,name=tls_settings,json=tlsSettings,proto3" json:"tls_settings,omitempty"`
	WireVersion    uint32                 `protobuf:"varint,3,opt,name=wire_version,json=wireVersion,proto3" json:"wire_version,omitempty"`
	ProfileVersion uint32                 `protobuf:"varint,4,opt,name=profile_version,json=profileVersion,proto3" json:"profile_version,omitempty"`
	Fallback       *FallbackConfig        `protobuf:"bytes,5,opt,name=fallback,proto3" json:"fallback,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerConfig) Reset() {
	*x = ServerConfig{}
	mi := &file_proxy_artx_config_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerConfig) ProtoMessage() {}

func (x *ServerConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proxy_artx_config_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerConfig.ProtoReflect.Descriptor instead.
func (*ServerConfig) Descriptor() ([]byte, []int) {
	return file_proxy_artx_config_proto_rawDescGZIP(), []int{2}
}

func (x *ServerConfig) GetUsers() []*protocol.User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *ServerConfig) GetTlsSettings() *tls.Config {
	if x != nil {
		return x.TlsSettings
	}
	return nil
}

func (x *ServerConfig) GetWireVersion() uint32 {
	if x != nil {
		return x.WireVersion
	}
	return 0
}

func (x *ServerConfig) GetProfileVersion() uint32 {
	if x != nil {
		return x.ProfileVersion
	}
	return 0
}

func (x *ServerConfig) GetFallback() *FallbackConfig {
	if x != nil {
		return x.Fallback
	}
	return nil
}

var File_proxy_artx_config_proto protoreflect.FileDescriptor

const file_proxy_artx_config_proto_rawDesc = "" +
	"\n" +
	"\x17proxy/artx/config.proto\x12\x0fxray.proxy.artx\x1a\x1acommon/protocol/user.proto\x1a#transport/internet/tls/config.proto\"\x1b\n" +
	"\aAccount\x12\x10\n" +
	"\x03psk\x18\x01 \x01(\tR\x03psk\"B\n" +
	"\x0eFallbackConfig\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x16\n" +
	"\x06origin\x18\x02 \x01(\tR\x06origin\"\x91\x02\n" +
	"\fServerConfig\x120\n" +
	"\x05users\x18\x01 \x03(\v2\x1a.xray.common.protocol.UserR\x05users\x12F\n" +
	"\ftls_settings\x18\x02 \x01(\v2#.xray.transport.internet.tls.ConfigR\vtlsSettings\x12!\n" +
	"\fwire_version\x18\x03 \x01(\rR\vwireVersion\x12'\n" +
	"\x0fprofile_version\x18\x04 \x01(\rR\x0eprofileVersion\x12;\n" +
	"\bfallback\x18\x05 \x01(\v2\x1f.xray.proxy.artx.FallbackConfigR\bfallbackBO\n" +
	"\x13com.xray.proxy.artxP\x01Z$github.com/xtls/xray-core/proxy/artx\xaa\x02\x0fXray.Proxy.ArtXb\x06proto3"

var (
	file_proxy_artx_config_proto_rawDescOnce sync.Once
	file_proxy_artx_config_proto_rawDescData []byte
)

func file_proxy_artx_config_proto_rawDescGZIP() []byte {
	file_proxy_artx_config_proto_rawDescOnce.Do(func() {
		file_proxy_artx_config_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proxy_artx_config_proto_rawDesc), len(file_proxy_artx_config_proto_rawDesc)))
	})
	return file_proxy_artx_config_proto_rawDescData
}

var file_proxy_artx_config_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_proxy_artx_config_proto_goTypes = []any{
	(*Account)(nil),        // 0: xray.proxy.artx.Account
	(*FallbackConfig)(nil), // 1: xray.proxy.artx.FallbackConfig
	(*ServerConfig)(nil),   // 2: xray.proxy.artx.ServerConfig
	(*protocol.User)(nil),  // 3: xray.common.protocol.User
	(*tls.Config)(nil),     // 4: xray.transport.internet.tls.Config
}
var file_proxy_artx_config_proto_depIdxs = []int32{
	3, // 0: xray.proxy.artx.ServerConfig.users:type_name -> xray.common.protocol.User
	4, // 1: xray.proxy.artx.ServerConfig.tls_settings:type_name -> xray.transport.internet.tls.Config
	1, // 2: xray.proxy.artx.ServerConfig.fallback:type_name -> xray.proxy.artx.FallbackConfig
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proxy_artx_config_proto_init() }
func file_proxy_artx_config_proto_init() {
	if File_proxy_artx_config_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proxy_artx_config_proto_rawDesc), len(file_proxy_artx_config_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proxy_artx_config_proto_goTypes,
		DependencyIndexes: file_proxy_artx_config_proto_depIdxs,
		MessageInfos:      file_proxy_artx_config_proto_msgTypes,
	}.Build()
	File_proxy_artx_config_proto = out.File
	file_proxy_artx_config_proto_goTypes = nil
	file_proxy_artx_config_proto_depIdxs = nil
}
